### ISSUE TITLE
悬浮脚注被代码块遮挡

### ISSUE THREAD

**Issue by Shitao5** [yihui/litedown#11]
小板凳搬好了 ~~催更~~。

发现悬浮的脚注会被代码块遮挡住：

![image](https://github.com/yihui/litedown/assets/68451957/1de2b011-9c80-4250-88f1-d39fd6fc12ba)

**Comment by Shitao5** [comment]
又看了一遍，还是[这个地方](https://yihui.org/litedown/#sec-footnotes_1)，在页面较窄的时候脚注从侧边来到正文，这里有两个单词成了漏网之鱼，其他脚注都正常，益辉大大看看是否可以一并修复。

![image](https://github.com/yihui/litedown/assets/68451957/a09f11cc-d9d6-4d4c-b5c2-f2e1de41d23f)

**Comment by Shitao5** [comment]
页面宽度再小一点的时候发现在脚注跑到行中去了：

![image](https://github.com/yihui/litedown/assets/68451957/ad68a07c-111d-4934-a65c-b15ca1c03615)

这个不确定是否设计如此，我觉得这也挺合理的，但估计有不少小伙伴会犯强迫症。

**Comment by CyrusYip** [comment]
> 页面宽度再小一点的时候发现脚注跑到行中去了：
>
> —— @Shitao5

这是[响应式设计](https://zh.wikipedia.org/zh-cn/%E5%93%8D%E5%BA%94%E5%BC%8F%E7%BD%91%E9%A1%B5%E8%AE%BE%E8%AE%A1)。宽度够大（1280px 以上）就在侧面放脚注，太小放不下就直接放文章里面了。

**Comment by Shitao5** [comment]
@CyrusYip  嗯嗯我理解，目前脚注放在段落里边了。我的常规理解是段落完整优先，脚注可以放在对应段落下面。

**Comment by yihui** [comment]
> 这个不确定是否设计如此，我觉得这也挺合理的，但估计有不少小伙伴会犯强迫症。

这个“强行插队”设计是我有意如此，我个人觉得插队更合理。如果不插队，那么就得接受更丑的结果：

<img width="646" alt="image" src="https://github.com/yihui/litedown/assets/163582/a8cb640e-388b-4a16-9ffd-58531d28a471">

> 我的常规理解是段落完整优先，脚注可以放在对应段落下面。

是的，只是从实现角度来说，这个单纯用 CSS 无法实现，必须要借用 JS，可能会使代码复杂许多。当然，欢迎你深入研究，也许并没有我说的那么复杂。

**Comment by yihui** [comment]
原始问题已修复（<https://github.com/yihui/misc.js/commit/41681fc1d520a3183e8aaae81e3e3a60deed4f9f>），就是个 z-index 的事。

> 在页面较窄的时候脚注从侧边来到正文，这里有两个单词成了漏网之鱼

也已修复：https://github.com/yihui/misc.js/commit/28c99ef2621a68e6903bbd5b1b8463477cf85f22
