### ISSUE TITLE
Wishlist:  An Option for Preserving YAML Headers in HTML Outputs

### ISSUE THREAD

**Issue by liao961120** [yihui/litedown#19]
Hi Yihui,

I'm really thrilled to see the newly implemented bibliography feature (#6). This got me thinking about the potential of using `litedown` to render Rmds into HTML fragments that could then be fed to a static site generator like Hugo.

The only obstacle (that I'm able to notice) is that the YAML header—which could also be used to specify options for a Hugo page—is currently excluded from the HTML output.

Is it possible (or are there any workarounds) to provide an option for keeping the YAML header in the HTML outputs, such as:

```markdown
---
output:
    litedown::html_format:
        template: FALSE
        keep_yaml: TRUE
---
```

Big thanks for the great work!

**Comment by yihui** [comment]
Yes, that should be simple enough to implement. I just submitted the first version of litedown to CRAN (#12), which is pending review. If they can finish the review relatively soon, I will consider adding this feature to the next dev version.

**Comment by liao961120** [comment]
Thanks, I'll definitely give `fuse_site()` a try!

**Comment by yihui** [comment]
Done.

Note that `keep_yaml: true` implies `template: false` so you don't need to set the latter.
