### ISSUE TITLE
[bug] page segmentation error

### ISSUE THREAD

**Issue by AlexZHENGH** [yihui/litedown#25]
When switching to page mode in [Litedown: R Markdown Reimagined](https://yihui.org/litedown/), I encountered an issue on page 36:

- The content overflows beyond the page boundaries (screenshot attached).
- Page 35 is completely skipped.

![image](https://github.com/user-attachments/assets/4113297a-a0c9-43d7-ac2b-0885b6b81df6)

This may be related to the fragmentation code mentioned in issue #21.

**Comment by yihui** [comment]
I remember that I ran into this bug some days ago and fixed it, but apparently it was re-introduced. I'll look into it again. Thanks for the report!

**Comment by yihui** [comment]
Fixed now.
