### ISSUE TITLE
How could I get started with litedown

### ISSUE THREAD

**Issue by yoonghm** [yihui/litedown#26]
Hi @yihui, I am new to R, Rmarkdown and litedown. I have used Quarto, however.

I have installed and started R and installed litedown. `litedown::fuse('test.Rmd')` will generate `test.html` on the same folder as source document.

I have tried 
1. `litedown::roam()`
2. `litedown::roam('C:/My', TRUE)` 

but nothing has appeared.

**Comment by yihui** [comment]
Please read the help page `?litedown::roam`. It's mainly for preview and doesn't generate output files during preview. If you need the output file, call `fuse()` or click on the lightning button on top right.
