### ISSUE TITLE
Inline r code output truncated to 3 digits

### ISSUE THREAD

**Issue by calvinw** [yihui/litedown#27]
Thanks for the excellent tool! It is very exciting....

I think that inline code output is being truncated to 3 digits sometimes for me:

I get this from the command line:

> litedown::fuse(text="Here is some inline code: `{r} 1.234`")
<p>Here is some inline code: 1.23</p>

Here is my sessionInfo:
R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] litedown_0.2

loaded via a namespace (and not attached):
[1] compiler_4.3.3   tools_4.3.3      codetools_0.2-19 xfun_0.47.5     
[5] commonmark_1.9.1

**Comment by yihui** [comment]
You are right. By default, numbers are truncated to 3 significant digits. You can adjust it via `options(litedown.inline.signif = N)`, where `N` is your desired number of digits.

**Comment by calvinw** [comment]
> You are right. By default, numbers are truncated to 3 significant digits. You can adjust it via `options(litedown.inline.signif = N)`, where `N` is your desired number of digits.

That is so excellent. Thanks very much.

**Comment by yihui** [comment]
You are welcome. A lot of things haven't been documented yet, but please feel free to ask questions anyway, so I have a better idea on which aspects of this package I should document first.

**Comment by yihui** [comment]
I've added doc at https://yihui.org/litedown/#sec:numeric-output

**Comment by yihui** [comment]
Sorry I dropped the options `litedown.inline.signif` and `litedown.inline.power`. The new way to set these options is through chunk options ` signif` and `power`, which makes it much easier to control the number formats individually: https://yihui.org/litedown/#sec:numeric-output

**Comment by calvinw** [comment]
> Sorry I dropped the options `litedown.inline.signif` and `litedown.inline.power`. The new way to set these options is through chunk options `signif` and `power`, which makes it much easier to control the number formats individually: https://yihui.org/litedown/#sec:numeric-output

Thanks.... a much better solution. the fine grained ability to do this makes perfect sense.
