### ISSUE TITLE
Change default html style for multiple authors

### ISSUE THREAD

**Issue by AlbertLei** [yihui/litedown#28]
When multiple authors exist, it might be better to list each author in a separate line?

```
---
author:
  - Zhang San
  - Li Si
date: "Sep 30, 2024"
---
```

Output: 

<img width="317" alt="image" src="https://github.com/user-attachments/assets/a7ef72a2-3480-474f-9fc4-2bcb635c9db9">

The config `_litedown.yml` is copied from the `docs/` folder of this repo.

**Comment by yihui** [comment]
That may be a good idea. Let me think more about it. Thanks!

**Comment by yihui** [comment]
Done.
