### ISSUE TITLE
print the full url when running `litedown::roam()`

### ISSUE THREAD

**Issue by AlbertLei** [yihui/litedown#29]
The docs claim:
> run `litedown::roam()` and it will launch a file browser to let
> you preview everything...

This feature works in RStudio, but it seems to apply to RStudio only?

When I run `litedown::roam()` in the vscode R terminal, a  file browser is not launched automatically. Even worse, the console prints nothing, with no error/warning info.

Suggestion: Print the full url (seems to be `http://127.0.0.1:xxxxx/custom/litedown/`) when running `roam()`

**Comment by yihui** [comment]
I haven't tried vscode, but the `roam()` preview is definitely not tied to RStudio. What you saw was a bug, which I just fixed.

I don't know if vscode has a viewer pane like RStudio. If it does, I wonder if `browseURL()` would open a URL in that pane.

P.S. To see the value of `roam()`, you can explicitly `print()` it, or wrap it in `()` (e.g., `(litedown::roam())`), or check `.Last.value` after running `litedown::roam()`.
