### ISSUE TITLE
Equations muddled with list markup

### ISSUE THREAD

**Issue by hturner** [yihui/litedown#33]
Equations with line breaks before operators that are valid markup for list bullets are not rendered correctly.

An example:

````
---
title: "Equation Bug"
output: 
  litedown::html_format:
    options:
      js_math: "katex"
knit: litedown:::knit
---

## Example

Equation with various operators that are also valid markup for list bullets

```
$$a * b - c + d$$
```
$$a * b - c + d$$ 

## Bad line breaks

Break before `*`, no preceding space
```
$$a 
* b - c + d$$
```
$$a 
* b - c + d$$ 

Break before `-`, one preceding space
```
$$a * b
 - c + d$$ 
```
$$a * b
 - c + d$$ 
 
Break before `+`, two preceding spaces
```
$$a * b - c
  + d$$ 
```
$$a * b - c
  + d$$ 
  
## Maybe bad line break

Break before `+`, four preceding spaces (not sure if junk output is hangover 
from bad examples)
```
$$a * b - c
    + d$$ 
```
$$a * b - c
    + d$$ 
    
## Good line break
    
Break after `-`, two preceding spaces
```
$$a * b - 
  c + d$$
```
$$a * b - 
  c + d$$
````

Renders as 

![image](https://github.com/user-attachments/assets/608c881c-14f1-4dee-a260-f863e0c97ecd)

Notes:
* I get the same results with KaTeX and MathJax.
* All equations render correctly with rmarkdown::html_document.

**Comment by yihui** [comment]
This is indeed a bug, and due to one of the two aspects that I dislike most about the commonmark spec (i.e., no requiring empty lines around block-level elements). The author of Pandoc also hates it: https://github.com/jgm/djot?tab=readme-ov-file#rationale (point 7). I think this is absolutely a design mistake, but I can't change the spec. I'll see if I can figure out a workaround. Thanks for the report!

**Comment by yihui** [comment]
Fixed now. However, please note that the current syntax for `$$ $$` expressions requires that there are no trailing spaces after the closing `$$`. Your examples have spaces after `d$$`, which must be removed.

**Comment by hturner** [comment]
Brilliant, thanks!
