### ISSUE TITLE
parsing latex strings inside parentheses

### ISSUE THREAD

**Issue by AlbertLei** [yihui/litedown#34]
litedown seems not parse latex strings inside parentheses. eg:

```md
The force ($F$) equals to mass ($m$) multiplied by the acceleration ($a$).
```

litedown output:

<img width="455" alt="image" src="https://github.com/user-attachments/assets/eedb7207-8937-4c9c-84c4-b6b515247c92">

Would you consider changing the latex parsing rule to allow this? The previosu example is parsed "correctly" by pandoc and github (see below)

- The force ($F$) equals to mass ($m$) multiplied by the acceleration ($a$).

**Comment by yihui** [comment]
Fixed in **xfun**. Thanks for the report! You can install the development version via

```r
remotes::install_github('yihui/xfun')
```

Or wait for an hour and

```r
install.packages('xfun', repos = 'https://yihui.r-universe.dev')
```

Make sure `packageVersion('') >= '0.48.5')` after installation.
