### ISSUE TITLE
Markdown output in front matter?

### ISSUE THREAD

**Issue by mikmart** [yihui/litedown#35]
I know I can `fuse()` an Rmd file to Markdown using `output = ".md"`.

``` r
litedown::fuse(c("```{r}", "1 + 1", "```", "", "$\\pi$ = `{r} pi`."), ".md")
#> 
#> ```{.r}
#> 1 + 1
#> ```
#> 
#> ```
#> #> [1] 2
#> ```
#> 
#> $\pi$ = 3.14.
```

Is there a way to specify Markdown output in the YAML front matter? I've tried:

``` r
doc <- c("```{r}", "1 + 1", "```", "", "$\\pi$ = `{r} pi`.")
yaml <- function(x) c("---", x, "---")
litedown::fuse(c(yaml("output: markdown"), doc))
```

    #> <!DOCTYPE html>
    #> <html>
    [snip]
    #> </html>

``` r
litedown::fuse(c(yaml("output: litedown::markdown_format"), doc))
#> Error in if (startsWith(output, "markdown:")) output = "markdown": missing value where TRUE/FALSE needed
```

``` r
litedown::fuse(c(yaml("output: litedown::commonmark_format"), doc))
#> Error in system.file(..., package = "litedown", mustWork = TRUE): no file found
```
For context: I'm trying to see if I can use litedown to render .Rmd to .md for Hugo.

**Comment by yihui** [comment]
Sounds like a bug (or two bugs). I'll investigate. Thanks for the report!

> For context: I'm trying to see if I can use litedown to render .Rmd to .md for Hugo.

Note that Hugo's Markdown renderer is not strictly compatible with litedown. If you use litedown features that are missing in Hugo, you may want to convert .Rmd to .html while keeping the YAML header instead; see #19.

**Comment by mikmart** [comment]
Thanks! I'll give that a go too.

**Comment by yihui** [comment]
Done. You can use `litedown::markdown_format` now.

**Comment by mikmart** [comment]
Thank you! 🎉
