### ISSUE TITLE
How to close the live preview app?

### ISSUE THREAD

**Issue by TimTaylor** [yihui/litedown#37]
Apologies if I have missed something obvious but is there a way to close the live preview app without closing the R session?

**Comment by yihui** [comment]
If you are in RStudio Viewer, use the broom button to clear the page. If you are in a web browser, close the browser page.

**Comment by yihui** [comment]
You are right. When the app doesn't have any active client connecting to it, it won't do anything and is harmless. Technically it is just a function registered in a special environment. If you do want to clean up that function, I can certainly provide a way to do it.

**Comment by yihui** [comment]
I just provided an internal function `xfun:::stop_app()` to close the app. I didn't export it because I don't think it will be used often, but it will be nice if it's possible anyway.
