### ISSUE TITLE
xquartz requirement

### ISSUE THREAD

**Issue by TimTaylor** [yihui/litedown#39]
Even after https://github.com/yihui/litedown/commit/5682a8c10b6b78bdb27580137553a681085b0612 I'm still seeing some issues on CI when no xquartz is installed.

I was trying to get to the bottom of a segfault in this minimal reprex over here https://github.com/TimTaylor/seg/commits/main/. The solution was to add xquartz to the install (see the final commit https://github.com/TimTaylor/seg/commit/3c94b9594e242a4c837e945e281bfe3efd7616c3).

Does more need to be done to handle a missing xquartz?

Apologies if this report is erroneous - I'm not a mac user so trying to get to the bottom of the failure with GitHub actions has been interesting :sweat_smile:

**Comment by yihui** [comment]
Thanks for the report! It seems I need to dig deeper.

**Comment by yihui** [comment]
Fixed now. I need to check the existence of `xquartz`.

**Comment by yihui** [comment]
**litedown** 0.4 is on CRAN, and this problem should be gone now. I have confirmed that my other packages using **litedown** to build vignettes no longer have this problem when `xquartz` is not installed.
