### ISSUE TITLE
Feature request: markdown_format

### ISSUE THREAD

**Issue by J-Moravec** [yihui/litedown#40]
I would like to setup my YAML header so that the document I get is markdown, i.e., the only thing that would happen is translating chunks.

1. The output format can be only `html_format` or `latex_format`
2. Setting output to `html_format` with `keep_md = TRUE` but this produces a different (much larger) HTML output then if the YAML header was not specified, and I wasn't able to suppress the default templates and meta.

On a side note, would it be possible to have the stdout (`echo = TRUE`) in the same chunk as the code?

I.e., the `.md` would look like this:

````
```{r}
print("foo")
#> [1] "foo"
```
````

btw. love seeing the pivot towards simplicity with and tinyvere with `litedown`. I have been heading to the same direction for some time as well and this really helps me prune the dependencies.

**Comment by yihui** [comment]
Duplicate of #35

**Comment by J-Moravec** [comment]
Ah, awesome. What confused me was that `litedown::latex_format` and `litedown::html_format` exist, but `litedown::markdown_format` doesn't.

**Comment by yihui** [comment]
This is just not documented yet...

**Comment by yihui** [comment]
> On a side note, would it be possible to have the stdout (`echo = TRUE`) in the same chunk as the code?

The chunk option `collapse = TRUE` has been implemented now.
