### ISSUE TITLE
Embedding resources within site defaults to incorrect url for R (prism)

### ISSUE THREAD

**Issue by TimTaylor** [yihui/litedown#52]
Without explicitly setting
```R
js_highlight:
        languages: [r]
```
When embedding resources in a site with a default configuration, litedown tries to download from
```
https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-R.min.js
```

when I think it should be using a lower case `r`

```
https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-r.min.js
```
For reference here's the wanring/output I'm seeing from curl/litedown
```
curl: (22) The requested URL returned error: 404
[0] Downloading 'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-R.min.js' ...
HTTP ERROR response 404  [https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-R.min.js]
Warning message:
In warn(l4, l3, d) :
  Unable to recognize code blocks with language(s): "R". They will not be syntax highlighted by prism.js. If you can find the right language files at https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/, you may mannually specify their names in the 'languages' field of the 'js_highlight' option.
```

Interestingly, the lower case version is actually embedded correctly in the rendered html so I guess this lower case version is being pulled in silently at another point.

Hope this makes sense.

**Comment by yihui** [comment]
Hmm, that's indeed interesting. I'll see what's going on later today (if you can figure it out by yourself, feel free to send a PR). The culprit might be one of these two functions:

https://github.com/yihui/litedown/blob/a26e5d8892fe3ba76a2e1a6285aaf9bc6d59b23d/R/utils.R#L251
https://github.com/yihui/litedown/blob/a26e5d8892fe3ba76a2e1a6285aaf9bc6d59b23d/R/utils.R#L309
