### ISSUE TITLE
YAML header "markdown::html_format" not detected

### ISSUE THREAD

**Issue by rikivillalba** [yihui/litedown#55]
When `litedown::fuse()` is called without specifying output format, then it is extracted from YAML 'output' value is used, then 'format' is selected from `md_formats` by key.
If format is "markdown::html_format" no format is found by key, thus a "missing when T/F expected" error is thrown in `startsWith()` 

Relevant code here
https://github.com/yihui/litedown/blob/main/R/utils.R#L159
https://github.com/yihui/litedown/blob/8b1e361b8919c0df2bda8f8da3722df7172a9bd0/R/utils.R#L161

Perhaps `if (is.na(output)) output = format` should be added next to that line to avoid _NA_character?

**Comment by yihui** [comment]
Sounds reasonable. Will do. Thanks for the suggestion!
