### ISSUE TITLE
Wishlist: support for bibliographies

### ISSUE THREAD

**Issue by hturner** [yihui/litedown#6]
About [~3k packages on CRAN use a `.bib` file](https://github.com/search?q=org%3Acran%20path%3A*.bib&type=code) in their vignette and there are more that embed the bibliography created from BibTeX. Of course bibliographies would also be common for other articles and books. So it would be great to have support for bibliographies in litedown.

A litedown user could generate their own bibliography without using BibTeX or Pandoc. One way is to create an "Rstyle" bibliography from a `.bib`file with the rbibutils package:

``` r
# create demo .bib file
txt <- "@Manual{R,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2024},
  url = {https://www.R-project.org/},
}
  
@Manual{Matrix,
  title = {Matrix: Sparse and Dense Matrix Classes and Methods},
  author = {Douglas Bates and Martin Maechler and Mikael Jagan},
  year = {2024},
  note = {R package version 1.7-0},
  url = {https://CRAN.R-project.org/package=Matrix},
}"
fileConn <- file("example.bib")
writeLines(txt, fileConn)
close(fileConn)

# convert .bib to R style
library(rbibutils)
bibConvert("example.bib", "bib.R", outformat = "Rstyle")
#> $infile
#> [1] "example.bib"
#> 
#> $outfile
#> [1] "bib.R"
#> 
#> $nref_in
#> [1] 2
#> 
#> $nref_out
#> [1] 2
```

Then use this R style bibliography to create citations and a bibliography using functions from base R (base, utils):

``` r
# create list of  bibentry objects
bib <- source("bib.R")$value

# equivalent of citet
cite("R, Matrix", bib, textual = TRUE)
#> [1] "R Core Team (2024); Bates, Maechler, and Jagan (2024)"

# equivalent of citep
cite("R, Matrix", bib)
#> [1] "(R Core Team 2024; Bates et al. 2024)"

# print bibliography ordered alphabetically
# uses plain text (markdown) style defined by bibstyle function
# will print whole bib, not just cited refs
sort(bib)
#> Bates D, Maechler M, Jagan M (2024). _Matrix: Sparse and Dense Matrix
#> Classes and Methods_. R package version 1.7-0,
#> <https://CRAN.R-project.org/package=Matrix>.
#> 
#> R Core Team (2024). _R: A Language and Environment for Statistical
#> Computing_. <https://www.R-project.org/>.
```

Maybe a litedown implementation could be based on this approach? Ideally from a user point of view it would be close to the rmarkdown approach (bib in YAML, @key or [@key] in text, automatically generate references at the end) so that old documents are easily converted. But a lighter version might just add some sugar to the above, e.g. Rstyle bib in YAML, citet and citep functions that automatically use this bibliography, generated bibliography of only cited references.

**Comment by yihui** [comment]
Thanks for the suggestion! Bibliography is the last major Markdown feature to be implemented: https://github.com/yihui/litedown/blob/9f5c93692795dc1dfc18efd073fe01fdccfd9a94/R/mark.R#L206

**Comment by yihui** [comment]
Implemented now (following your suggestion).

I ended up not using the `cite()` function since I need to add links onto citations for HTML output, and I just tried to extract the author-year information by myself.

**Comment by hturner** [comment]
Great, thanks!
