### ISSUE TITLE
Wishlist: support for abstract

### ISSUE THREAD

**Issue by hturner** [yihui/litedown#7]
About [800 packages on CRAN use an abstract in their vignette](https://github.com/search?q=org%3Acran+%28%5Cbegin%7Babstract%7D+OR+%2F%5Eabstract%5B%3A%5D%2F%29&type=code), so this is not as high priority as #6, but may be easier to implement.

Following the rmarkdown approach, the abstract could be specified in the YAML, then it just requires some CSS to style it.

**Comment by yihui** [comment]
Good idea. Will do.

**Comment by yihui** [comment]
Done. Thanks!
