### ISSUE TITLE
Mention fig.alt in the docs

### ISSUE THREAD

**Issue by hturner** [yihui/litedown#8]
I'm happy to see that `fig.alt` is supported by litedown, but there is no mention of it in [the docs](https://github.com/yihui/litedown). Since this was not always possible with rmarkdown I think it is worth including in an example or mentioning explicitly somewhere.

**Comment by yihui** [comment]
Yes, the documentation needs a lot more work (which may take two months). Not only `fig.alt`, but most chunk options are not documented yet.

**Comment by yihui** [comment]
I've finally finished documenting all chunk options (my brain hurts now). Unfortunately GIthub Action on macOS is [currently broken](https://github.com/yihui/litedown/actions/runs/12004130069/job/33458621572) so the website can't be automatically deployed. I'm not sure [when it will resume](https://forum.posit.co/t/r-cmd-check-fails-on-macos-latest-release-r-lib-actions-setup-r-v2/195084). You can clone the repo and preview the docs by yourself:

```r
install.packages(c('litedown', 'xfun'), repos = 'https://yihui.r-universe.dev')
# then run litedown::roam() in this package's root directory
```

**Comment by remlapmot** [comment]
If you want an immediate fix - there is a workaround to fix the macOS action https://github.com/r-lib/actions/issues/948#issuecomment-2495861299

**Comment by yihui** [comment]
@remlapmot Thank you! It seems they have applied the workaround in the setup-r action: https://github.com/r-lib/actions/pull/953 I just re-ran the action and it worked.

@hturner @TimTaylor `fig.alt` is documented at https://yihui.org/litedown/#sec:option-fig
